name: Publish Release

on:
  workflow_run:
    workflows: ["Unit Testing"]
    types:
      - completed
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    if: |
      github.repository == 'run-llama/llama_extract' &&
      (github.event_name == 'workflow_dispatch' ||
       (github.event_name == 'workflow_run' &&
        github.event.workflow_run.name == 'Unit Testing' &&
        github.event.workflow_run.conclusion == 'success'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.14
        with:
          password: ${{ secrets.LLAMA_EXTRACT_PYPI_TOKEN }}
